# Generated by Django 2.0.2 on 2018-05-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='user',
            new_name='author',
        ),
    ]
