# Generated by Django 2.0.2 on 2018-05-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20180519_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
