# Generated by Django 2.0.2 on 2018-05-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20180519_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
