# Generated by Django 2.0.2 on 2018-05-19 10:30

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_song_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to=music.models.user_directory_path),
        ),
    ]
